apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: credit-api
  namespace: #{AKS_NAMESPACE}#
  annotations:
    nginx.ingress.kubernetes.io/enable-access-log: "false"
spec:
  tls:
  - hosts:
    - #{INGRESS_HOST}#
    secretName: credit-cert
  rules:
  - host: #{INGRESS_HOST}#
    http:
      paths:
      - path: /
        backend:
          serviceName: credit-api
          servicePort: 80